### ISSUE TITLE
Relation of spatial resolution on Dataset, Distribution and Data Service

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/GeoDCAT-AP#100]
**Motivation**
In GeoDCAT-AP 2.0.0 properties like spatial resolution are optional on [Dataset](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#dataset-spatial-resolution), [Distribution](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#distribution-spatial-resolution) and [Data Service](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#data-service-spatial-resolution).

Given that Distributions are representations of a Dataset, and a Data Service may serve multiple Datasets, what are the relations of spatial resolution specifications on these classes?

**Questions**
The open questions are:
1. Can a Distribution have a different spatial resolution than the Dataset?
    1. If no, why do we need the property both on a Dataset and a Distribution?
    2. If yes
        1. Should all Distributions of a Dataset have the same spatial resolution as the Dataset?
        2. Should the Dataset be tagged by all the different spatial resolutions found in its Distributions?
2. Do all datasets served by a Data Service have the same spatial resolution as the Data Service?
...

**Comment by VeronikaKusova** [comment]
We had a discussion about this issue (Czech Office for Surveying, Mapping and Cadastre and Czech Environmental Information Agency). From our point of view it is not necessary to have the information about spatial resolution on a Dataset and a Distribution as well. And for example in ISO 19115 there isn’t stated spatial resolution in the MD_Distribution part.

**Comment by jakubklimek** [comment]
The following resolution was approved during the webinar:

1. For Distribution, spatial resolution [0..1] represents the spatial resolution of the described file.​
2. For Data Service – spatial resolution [0..n] describes the capabilities of the data service, i.e. in which spatial resolutions it can serve data.​
3. For Dataset – spatial resolution [0..**n**] describes the spatial resolution of **the original** data in the dataset, i.e. regardless of how it is distributed using distributions.​
4. For Dataset Series – unclear what spatial resolution of a dataset series means.​
