### ISSUE TITLE
Geographic name optional, yet `1..n`

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/GeoDCAT-AP#104]
**Problem statement**
In GeoDCAT-AP 2.0.0, `geographic name` on `Location` [is defined with multiplicity `1..n`](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#location-geographic-name) even though it is listed in the optional properties section.

This seems like a bug.

**Proposal**
Relax the multiplicity to `0..n`

**Comment by uvoges** [comment]
In the UML it looks different...(no geo-identifier provided)=I guess bug:
<img width="115" alt="Screenshot 2024-06-03 125119" src="https://github.com/SEMICeu/GeoDCAT-AP/assets/12135911/3bceca91-b5ba-47b3-b0c8-cd071af63bb0">

**Comment by uvoges** [comment]
Maybe a vocabulary for the geographic identifier should be proposed as well....

**Comment by jakubklimek** [comment]
@uvoges There are various vocabularies for geographic identifiers already, see [Continent](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/continent), [Countries and terriotires](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/country), [Place](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/place), etc.

Do you have some specific proposal in mind? If yes, please create a separate issue as this one is about geographic name, not identifier.

**Comment by uvoges** [comment]
Maybe Geonames or an equivalent vocabulary provided by the EU

**Comment by jakubklimek** [comment]
@uvoges Yes, Geonames is one of those, see [A.7.10.2 Geographic identifier](https://semiceu.github.io/GeoDCAT-AP/releases/3.0.0/#geographic-identifier)
