### ISSUE TITLE
Clarify the meaning of multiple values of spatial coverage

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/GeoDCAT-AP#107]
**Problem statement**
With multiple values for spatial coverage allowed e.g. for a [dataset](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#dataset-spatial-coverage), it may not be clear enough, what the interpretation of those multiple values should be based on the current usage note:
>This property refers to a geographic region that is covered by the Dataset.

This is also an issue in DCAT-AP in general.

Example 1 - here we have a collection of possible spatial expressions that migh fit:
```turtle
<ds> dct:spatial _:Belgium .
<ds> dct:spatial _:Brussels .
<ds> dct:spatial _:Antwerp .
```

Example 2 - using in addition, different ways of representation of spatial coverage:
```turtle
<ds> dct:spatial _:Belgium .
<ds> dct:spatial [ dct:identifier _:Brussels ] .
<ds> dct:spatial [ skos:prefLabel "Antwerp"@en ] .
<ds> dct:spatial [ dcat:bbox """{ "type": "Polygon", "coordinates": [[
      [ 2.345693352852237, 51.705922095507674 ],
      [ 2.345693352852237, 49.478466262366766 ],
      [ 6.50311285587884, 49.478466262366766 ],
      [ 6.50311285587884, 51.705922095507674 ],
      [ 2.345693352852237, 51.705922095507674 ]
]]}"""^^<http://www.opengis.net/ont/geosparql#geoJSONLiteral>
   ]
```

**Proposal**
Explicitly say in a usage note that when multiple values are used for spatial coverage, this may be interpreted as a spatial union, or as alternative representations of spatial coverage that might fit, with no explicit spatial relation, to give guidance to implementers as to how to treat the multiple values of spatial coverage.

**Comment by jakubklimek** [comment]
Proposal accepted during webinar.

**Comment by uvoges** [comment]
spatial union, is fine with me.- +1
