### ISSUE TITLE
Revise usage of Licenses and Rights

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/GeoDCAT-AP#113]
**Problem statement**
GeoDCAT-AP 2.0.0 allows users to express a license document [as a text](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#licence-document-licence-text). This is not allowed in the context of High-Value Datasets (HVDs), where licences need to be structured and machine readable, i.e. identified by a dereferencable URL, preferrably from the [Licence EU NAL](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/licence) or [mapped to it](https://semiceu.github.io/uri.semic.eu-generated/DCAT-AP/releases/2.2.0-hvd/#c3).

However, even besides HVDs, license document should be properly structured documents, published somewhere, where they have a URL. Therefore, a representation of a license document using a simple literal does not seem to be sufficient.

In addition, the examples of usage in the current GeoDCAT-AP seem more like Rights statements, than actual Licences:

```turtle
[] dct:license [ a dct:LicenseDocument ;
    rdfs:label """
        The dataset contains parts which are restricted 
        by the data providers and not to be made public. 
        For further information and specification regarding 
        the use limitations and constraints please consult 
        the file WISE_WFD_ReferenceSpatialDataSets_2020-04-02.pdf 
        which is provided together with the data.    
      """@en ] ;
``` 

Moreover, [Example 41](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#ex-mapping-conditions-for-access-and-use) uses `dct:accessRights` without the code lists that should be used to represent Access rights. This seems incorrect and again is a more an example of `dct:rights`:
```turtle
dct:accessRights [ a dct:RightsStatement ;
    rdfs:label """
        public access limited according to Article 13(1)(b) 
	of the INSPIRE Directive
      """@en ] ] 
```

Also related to #82 

**Proposal**
1. Remove [license as text](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#licence-document-licence-text) and allow license usage only with license IRIs, and
2. Change mappings of non-IRI rights statements to RightsStatements, using `dct:rights`

**Comment by hallinpihlatie** [comment]
FYI:

Data providers may have their own licenses or use constraints. We have added use constraints to the ConditionsApplyingToAccessAndUse.rdf from the INSPIRE registry. They all include URIs. For example EMODNET license http://tupa.gtk.fi/paikkatieto/lisenssi/emodnet_licence.pdf
They are not "open data licenses" as it is recommended to use an international eg. CC-family license always when possible.

In cases where "No conditions to access and use" http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply remapping required for HVD isn't possible. Using this code value is ok INSPIRE but not for the Open Data Directive as I see it.

**Comment by jakubklimek** [comment]
Resolution approved during webinar.
