### ISSUE TITLE
Dataservice protocol list

### ISSUE THREAD

**Issue by joachimnielandt** [SEMICeu/GeoDCAT-AP#115]
In Flanders we use *conformsTo* to indicate with which standards the entity complies.
- there is no universal list of standards available
- the definition of a standard can be interpreted broadly or narrowly
- there is a strong connection between standards and typing of an entity, e.g., an entity is of the type `registry service` if it offers data according to the `ISO 19115` standard

| class            | definition / use                                                                                                |
|------------------|-----------------------------------------------------------------------------------------------------------------|
| Catalogus        |                                                                                                                 |
| Catalogus Record | The (metadata) standard to which the main subject of the Catalogus Record conforms.                             |
| Dataset          | A standard, schema, application profile, vocabularium, feature catalogue to which the dataset conforms.         |
| Distributie      | A standard, schema, implementation model, application profile, vocabularium to which the distribution conforms. |
| Dataservice      | A protocol (conform to Protocol, not to Standard) to which the dataservice conforms.                            |

- Datasets are conform to a standard.
- Distributions are conform to a *specialised* version of the standard of their dataset.
- **Services are conform to a protocol instead**, which is defined by a Flemish protocol list:
        - https://data.vlaanderen.be/id/concept/dataserviceprotocol/.
        - https://github.com/Informatievlaanderen/OSLOthema-metadataVoorServices/blob/master/codelijsten/protocol.ttl

This dataservice protocol list could be of interest to other parties. Would this be beneficial on a European level? Is this already available?

**Comment by jakubklimek** [comment]
@joachimnielandt See #114 - the INSPIRE list of protocols is linked from there. It seems to be a subset of what you are linking.
I think it might be of interest on a European level, as there is currently no EU NAL for service protocols, only file types.

**Comment by joachimnielandt** [comment]
It is important to note that we are linking various entity types to different standards, thereby creating an implicit registry of standards. This does not only encompass the list of protocols.

**Comment by jakubklimek** [comment]
@joachimnielandt Yes, but this issue is about data service protocol lists, and therefore is connected to the new `geodcatap:serviceProtocol` property and the INSPIRE Protocol values codelist.

A list of generic standards should be a separate issue, as the governance of such registry of standards will probably be different than a narrowly scoped list of data service protocols.
