### ISSUE TITLE
Format Publications Office

### ISSUE THREAD

**Issue by joachimnielandt** [SEMICeu/GeoDCAT-AP#119]
When mapping ISO to DCAT Distributions, the list of formats by the EU Publications Office is used (https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/file-type) in Flanders. We would suggest that this list is used by all parties (mentioned in a usage note?).

**Comment by jakubklimek** [comment]
Actually, this is already specified by GeoDCAT-AP 2.0.0 in the [Controlled Vocabularies section](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#controlled-vocabularies).
