### ISSUE TITLE
Info: on distribution / dataservice mapping rules

### ISSUE THREAD

**Issue by joachimnielandt** [SEMICeu/GeoDCAT-AP#120]
The following describes the mappings to dcat distributions and dataservices, deployed in Flanders. This ticket serves to share the approach and boost a discussion around the core mapping of ISO INSPIRE to GeoDCAT-AP.

Below there are two rules for Distributions: the first is the obvious case where the data is shared as a downloadable file, the second corresponds to a more interactive distribution where an API must be consumed to download the whole dataset. The third rule is about Data Services.

Observe that in our case the INSPIRE simplication for metadata was not performed for our ISO INSPIRE metadata. Consequently the Data Services do not have to be derived from `transferOptions/OnlineResources` embedded in a `Dataset`. They are independently documented. And this structure closely corresponds to the DCAT resources. Therefore the challenge is more situated at creating proper interlinked DCAT resources of datasets, distributions and data services.  

# Create dcat distribution (downloadable)
for `MD_ScopeCode = 'dataset'`
map each `gmd:transferOptions > gmd:CI_OnlineResource`
if `protocol in ['WWW:DOWNLOAD-1.0-ftp--download', 'WWW:DOWNLOAD-1.0-http--download', 'LINKdownload-store']`

`gmd:CI_OnlineResource/gmd:linkage/gmd:URL` is mapped to the required `dcat:accessURL`

| ISO         | GeoDCAT-AP VL              |
|-------------|----------------------------|
| Name        | title              |
| Description | description |
| Linkage     | accessURL                 |
| Format      | format                     |

Formats are taken from the list provided by the EU Publications Office (https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/file-type), also discussed in #119.

# Create dcat distribution (specific layer of downloadable service)
for `MD_ScopeCode = 'dataset'`
map each `gmd:transferOptions > gmd:CI_OnlineResource`
if `protocol in ['getMap/getTile', 'getFeature/getCoverage']`

| Attribute             | Description                                                                                               |
|-----------------------|-----------------------------------------------------------------------------------------------------------|
| accessURL             | (GDI-Vlaanderen) limited URL                                                                              |
| accessService   | Dataservice that responds to the query                                                                    |
| alternativeIdentifier (adms:identifier) | The parameter that identifies the distribution data in a geoservice                                       |
| description           | Default message: `The accessURL refers to a limited set of data, as defined in the GDI-Vlaanderen terms.` |

Example `alternativeIdentifier`:
```rdf
<ex:distributie1>adms:identifier[
_:skos:notation"<laag>" ^^ <wms:Layer>.
]
```

For the various service types, the following literal type (?) is used:
| Distribution | Service entity | Literal type                                           |
|--------------|----------------|--------------------------------------------------------|
| WMS          | Layer          | http://www.opengis.net/wms#Layer                       |
| WMTS         | Layer          | http://schemas.opengis.net/wmts#Layer (not resolvable) |
| WFS          | Feature        | http://www.opengis.net/wfs#FeatureType                 |
| WCS          | Coverage       | http://www.opengis.net/wcs#CoverageDescription         |

Example use cases:
- third party application uses the ISO distribution (that offers the GetMap protocol) to refer to the map visualisation.
- a catalog user wants to integrate with data-offering applications, e.g., visualisations, based on the description of a distribution / dataset.

Reasoning:
- An ISO distribution with protocol GetMap refers to a specific *layer* in a dataservice.
- This aligns with our download / file interpretation of distributions.
- The *layer* parameter determines the complete content of the dataset.
- Downloadability is still possible, although inefficient.

# Create dcat dataservice
for each type (WMS, WFS, ...) of `MD_ScopeCode = service`
map 1 service operation to `dcat:endpointURL` and `dcat:endpointDescription`

**Comment by uvoges** [comment]
This is arelated issue I guess: https://github.com/SEMICeu/GeoDCAT-AP/issues/123
