### ISSUE TITLE
pitfalls for metadata providers regarding expected mapping of distributions , digitaltransfers from ISO19115/19139 metadata to GeoDCAT-AP

### ISSUE THREAD

**Issue by uvoges** [SEMICeu/GeoDCAT-AP#123]
in this issues I would like to collect pitfalls for metadata providers regarding distributions , digitaltransfers when mapping ISO19115/ISO19139 tdigitaltransferoptions (as provided in INSPIRE)  to GeoDCAT-AP which is e.g. upon harvesting..... 
The links defined in the ISO19115 md:distributionInfo/gmd:MD_Distribution/gmd:transferOptions are mapped to different  GeoDCAT-AP distribution resources with different fields in the DCAT-AP representation of the metadata depending on the codeListValue defined in the gmd:function element. Only gmd:transferOptions with the codeListValues 'download', 'offlineAccess' or 'order' are mapped to dcat distributions. gmd:transferOptions with the codeListValues 'information' or 'search' are mapped as foaf:page if no gmd:function element is defined the links are mapped as dcat:landingPage. These links still exist in the metadata but are not displayed as distributions e.g. in the data.europa.eu portal. 
The following ISO metadata will be mapped to a distribution:
```xml
    <gmd:MD_Distribution>
        <gmd:transferOptions>
            <gmd:MD_DigitalTransferOptions>
                <gmd:onLine>
                    <gmd:CI_OnlineResource>
                        <gmd:linkage>
                            <gmd:URL>https://example.com/download-link</gmd:URL>
                        </gmd:linkage>
                        <gmd:name>
                            <gco:CharacterString>Download dataset</gco:CharacterString>
                        </gmd:name>
                        <gmd:function>
                            <gmd:CI_OnLineFunctionCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue="download" />
                        </gmd:function>
                    </gmd:CI_OnlineResource>
                </gmd:onLine>
                <gmd:onLine>
                    <gmd:CI_OnlineResource>
                        <gmd:linkage>
                            <gmd:URL>https://example.com/information-link</gmd:URL>
                        </gmd:linkage>
                        <gmd:name>
                            <gco:CharacterString>information</gco:CharacterString>
                        </gmd:name>
                        <gmd:function>
                            <gmd:CI_OnLineFunctionCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue="information" />
                        </gmd:function>
                    </gmd:CI_OnlineResource>
                </gmd:onLine>
            </gmd:MD_DigitalTransferOptions>
        </gmd:transferOptions>
    </gmd:MD_Distribution>
</gmd:distributionInfo> 
```

**Comment by jakubklimek** [comment]
@uvoges The situation you describe is the result of the GeoDCAT-AP ISO to DCAT-AP mapping - since the links are not mapped to DCAT-AP Distributions, they are not displayed as distributions in data.europa.eu.
This is on purpose, as decided during previous work on [GeoDCAT-AP XSLT script](https://github.com/SEMICeu/iso-19139-to-dcat-ap/tree/dev), part of the work on GeoDCAT-AP 2.0.0 (and this in particular probably even 1.0.0.), as these links (`information` and `search`) do not link to `A physical embodiment of the Dataset in a particular format.`, which is the definition of DCAT-AP Distributions, therefore, this is also in line with expectations on DCAT-AP metadata records and their visualization.
