### ISSUE TITLE
Mapping of ISO metadata datestamp to DCAT

### ISSUE THREAD

**Issue by uvoges** [SEMICeu/GeoDCAT-AP#124]
Generally the DCAT-AP metadata only contains information about the data itself not the metadata. That means that the date from the gmd:dateStamp attribute is not mapped to DCAT-AP as it is about the metadata not the data. This mapping is important as the metadata datestamp is important for harvesting purposes.This should be clarified in GeoDCAT-AP

**Comment by jakubklimek** [comment]
Actually, this is mapped to DCAT-AP's `dcat:CatalogRecord`, specifically `dcterms:modified`, as can be seen in [this example](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#ex-mapping-temporal-reference) and [these lines of the XSLT](https://github.com/SEMICeu/iso-19139-to-dcat-ap/blob/1d29ac48bffb592796aab834d25417308b75f277/iso-19139-to-dcat-ap.xsl#L756-L768).

**Comment by uvoges** [comment]
Jakub, Do you think 2 datestamps are needed the one of the original metadata item  which is being mapped and of the actual DCAT Catalog Record entry?
...taking into account different harvesting scenarios...?

**Comment by jakubklimek** [comment]
Well, the original metadata item is **represented by** the DCAT Catalog Record - so they should be the same thing. Do you have another opinion?

**Comment by uvoges** [comment]
No, would be fine with me
