### ISSUE TITLE
Mapping ISO dates to GeoDCAT-AP

### ISSUE THREAD

**Issue by uvoges** [SEMICeu/GeoDCAT-AP#125]
There are three dates from the ISO metadata (metadata related to the data/Ressouce) that are mapped to DCAT-AP when present, the creation date, the publication date and the date of the last modification. I guess the corresponding XPath in ISO19115/19139 is: `gmd:identificationInfo/(srv:SV_ServiceIdentification|gmd:MD_DataIdentification)/gmd:citation/gmd:CI_Citation/gmd:date`. 
The dates are mapped according to their `CI_DateTypeCode`. Different codeListValues are mapped to different elements in DCAT-AP. 
Example: DCAT-AP: `dct:issued` - This is the Date of publication
```xml
 <dct:issued rdf:datatype="http://www.w3.org/2001/XMLSchema#date">2010-10-05</dct:issued>	
```
mapping from ISO19115-Xpath:

```
/MD_Metadata/identificationInfo/MD_DataIdentification/citation/CI_Citation/date/CI_Date/date/gco:Date[/MD_Metadata/identificationInfo/MD_DataIdentification/citation/CI_Citation/date/CI_Date/dateType/CI_DateTypeCode==‘publication‘]
```

The list below shows the different mappings to DCAT-AP:
| codelListValue   | DCAT-AP |
| ------------- | ------------- |
| creation  | `dct:created`  |
| publication  | `dct:issued`  |
| revision	| `dct:modified`  |

**Comment by jakubklimek** [comment]
@uvoges What you describe is also described in [B.6.11 Temporal reference and metadata date –*Additional extent information for the dataset (vertical and temporal) and *Metadata date stamp](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#temporal-reference-and-metadata-date-additional-extent-information-for-the-dataset-vertical-and-temporal-and-metadata-date-stamp) and handled [here in the XSLT](https://github.com/SEMICeu/iso-19139-to-dcat-ap/blob/1d29ac48bffb592796aab834d25417308b75f277/iso-19139-to-dcat-ap.xsl#L2667-L2698).

What is your suggestion here?
