### ISSUE TITLE
The representation of the spatialResolution should be clearer specified and explained

### ISSUE THREAD

**Issue by uvoges** [SEMICeu/GeoDCAT-AP#126]
For the spatial Resolution , I have seen different diverging representations:
e.g:
```xml
   <dcat:spatialResolutionInMeters rdf:datatype="http://www.w3.org/2001/XMLSchema#decimal">0.5</dcat:spatialResolutionInMeters>
```
or:
```xml
    <dqv:hasQualityMeasurement>
      <dqv:QualityMeasurement>
        <dqv:isMeasurementOf rdf:resource="http://data.europa.eu/930/spatialResolutionAsDistance"/>
        <dqv:value rdf:datatype="http://www.w3.org/2001/XMLSchema#decimal">0.5</dqv:value>
        <ns0:unitMeasure rdf:resource="http://www.qudt.org/vocab/unit/M"/>
      </dqv:QualityMeasurement>
    </dqv:hasQualityMeasurement>
```
or:
```xml
    <dqv:hasQualityMeasurement>
      <dqv:QualityMeasurement>
        <dqv:isMeasurementOf rdf:resource="http://data.europa.eu/930/spatialResolutionAsScale"/>
        <dqv:value rdf:datatype="http://www.w3.org/2001/XMLSchema#decimal">0.002</dqv:value>
      </dqv:QualityMeasurement>
    </dqv:hasQualityMeasurement>
```

**Comment by jakubklimek** [comment]
These options are described in [B.6.13 Spatial resolution – Spatial resolution of the dataset](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#spatial-resolution-spatial-resolution-of-the-dataset). What is your suggestion here?

**Comment by uvoges** [comment]
I would propose o use the same semantic (model) as in ISO19115- see MD_Resolution
also the Spatial resolution as vertical distance should be defined, seeISO19115:  extent /vertical Extent….

**Comment by jakubklimek** [comment]
@uvoges What specifically do you see as different/problematic?

Regarding the vertical distance, please open a separate issue for this, so that it can be addressed specifically. This is probably one of the places where the mapping is incomplete and no one requested this to be present in GeoDCAT-AP yet.

**Comment by uvoges** [comment]
ther is a discussion on this in GeoDCAT-AP:  [https://github.com/SEMICeu/GeoDCAT-AP/issues/15](https://github.com/SEMICeu/GeoDCAT-AP/issues/15)

**Comment by uvoges** [comment]
alight-weight solution similar to(in addition to spatial resolution in meters)
equivalentScale:
.. MD_RepresentativeFraction
.. denominator: 50000

**Comment by jakubklimek** [comment]
The current state of representation of spatial resolution is the result of the discussion in #15. For spatial resolution as vertical distance, there is a [corresponding metric](https://semiceu.github.io/GeoDCAT-AP/930/releases/3.0.0/#instances-of-metric) usable with [spatial resolution](https://semiceu.github.io/uri.semic.eu-generated/GeoDCAT-AP/releases/3.0.0/#Dataset.spatialresolution) using DQV.

Spatial resolution in meters is there for compatibility with DCAT-AP.

I still do not see what you percieve as problematic or what you propose to do.
