### ISSUE TITLE
The new GeoDCAT-AP should be defined as profile of the upcoming OGC GeoDCAT Specification

### ISSUE THREAD

**Issue by uvoges** [SEMICeu/GeoDCAT-AP#127]
The new GeoDCAT-AP should be defined as profile of the upcoming OGC GeoDCAT Specification,see:[https://www.ogc.org/press-release/ogc-forms-new-geodcat-standards-working-group/](url)

**Comment by jakubklimek** [comment]
This is indeed the goal, see [the introductory webinar](https://joinup.ec.europa.eu/collection/semic-support-centre/event/introductory-webinar-revision-geodcat-ap) and the [third webinar with progress update](https://joinup.ec.europa.eu/collection/semic-support-centre/event/third-working-group-webinar-revision-geodcat-ap). However, the timelines do not align, as GeoDCAT-AP 3.0.0 is about to be released this year and the work on GeoDCAT is going slower.

**Comment by uvoges** [comment]
understood, thanks
