### ISSUE TITLE
applicableLegislationrequired for geospatial HVD´s

### ISSUE THREAD

**Issue by uvoges** [SEMICeu/GeoDCAT-AP#129]
a future geodcatap must assure that the attribute dcatap:applicableLegislation is included as this is required for geospatial HVD´s  metadata (current DCAT-AP-HVD)

**Comment by jakubklimek** [comment]
Yes, there will be a section and a link to [DCAT-AP HVD](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/) which states this requirement for HVDs.
