### ISSUE TITLE
Typo in Usage note of Catalogued Resource - Catalogued Record

### ISSUE THREAD

**Issue by uvoges** [SEMICeu/GeoDCAT-AP#130]
the text "This class Catalogued Record is an abstract class for DCAT-AP. Therefore only subclasses should be used in a data exchange"
must be changed into:
"This class Catalogued Resource is an abstract class for DCAT-AP. Therefore only subclasses should be used in a data exchange"

**Comment by jakubklimek** [comment]
Fixed in https://semiceu.github.io/GeoDCAT-AP/drafts/3.0.0/
