### ISSUE TITLE
Catalogue Record: Attribute source metadata should be specified in more detail

### ISSUE THREAD

**Issue by uvoges** [SEMICeu/GeoDCAT-AP#131]
It is not clear what should be provided here and with which ncoding, e.g. ISO19115/ISO19139 xml code. I would prefer to use instead a link of specified type to the original metadata source if existing

**Comment by jakubklimek** [comment]
The range of the property [CatalogueRecord.sourceMetadata](https://semiceu.github.io/uri.semic.eu-generated/GeoDCAT-AP/releases/3.0.0/#CatalogueRecord.sourcemetadata) is CatalogueRecord, meaning the value is to be an IRI, which will be treated as an instance of CatalogueRecord.

This seems compliant with what you describe.
