### ISSUE TITLE
A.2 Motivation and use cases - Link to EU OPD should be deleted

### ISSUE THREAD

**Issue by akuegeler** [SEMICeu/GeoDCAT-AP#132]
A small change is needed in "A.2 Motivation and use cases" in https://github.com/SEMICeu/GeoDCAT-AP/blob/gh-pages/drafts/3.0.0/index.html

**Current text:**
_..."such as the [European Union Open Data Portal](http://data.europa.eu/euodp/) (EU ODP) and the [European Data Portal](http://data.europa.eu/europeandataportal/) (EDP)._"

**Change to:**
_...such as [data.europa.eu](https://data.europa.eu/), the official portal for European data._

**Reason:**
There are no longer two European data portals since ODP and EDP were combined in 2021. The official name for the current portal is data.europa.eu.

Thanks!
Antje Kügeler, con terra (contractor working on data.europa.eu)

**Comment by jakubklimek** [comment]
Fixed in https://semiceu.github.io/GeoDCAT-AP/drafts/3.0.0/
