### ISSUE TITLE
Alignment of GeoDCAT-AP and DCAT-AP 2.0.0

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/GeoDCAT-AP#14]
Is there any alignment of GeoDCAT-AP and DCAT-AP 2.0.0 planned at the moment? Specifically regarding the representation of services in DCAT-AP 2.0.0, which could be utilized in the context of GeoDCAT-AP. (#10)

**Comment by dr-shorthair** [comment]
And also to adopt the Time-and-Space recommendations, which are much more prescriptive in DCAT v2

**Comment by andrea-perego** [comment]
In view of a new release of GeoDCAT-AP, I've prepared a working draft of the specification, which could be possibly used as a starting point. It's in a separate branch - preview here:

https://raw.githack.com/SEMICeu/GeoDCAT-AP/develop/drafts/latest/

Compared with the previous versions of the GeoDCAT-AP specification, this draft follows the structure of the DCAT-AP specification, focussing on the description of the vocabulary, whereas the mappings have been moved to the appendix.

I've also prepared an updated version of the GeoDCAT-AP XSLT in the relevant repository, maintained in a separate branch:

https://github.com/SEMICeu/iso-19139-to-dcat-ap/tree/develop

The implemented revisions are documented in the changelog:

https://github.com/SEMICeu/iso-19139-to-dcat-ap/blob/develop/CHANGELOG.md

IMO, the revision should not be problematic, as the relevant changes in DCAT 2, and inherited by DCAT-AP 2, are basically compatible with the GeoDCAT-AP approach - modulo the use of different classes and properties. There are anyway a couple of issues that I will record in the tracker.

**Comment by andrea-perego** [comment]
Update:

The first working draft of GeoDCAT-AP 2.0.0 is out for public review (see announcement at https://github.com/SEMICeu/DCAT-AP/issues/167):

https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/

The new version of the XSLT has also been merged into the master branch (https://github.com/SEMICeu/iso-19139-to-dcat-ap/pull/2), and can be tested via the working demo of the GeoDCAT-AP API:

http://geodcat-ap.semic.eu/api/

**Comment by andrea-perego** [comment]
Closing following the publication of the first working draft for GeoDCAT-AP 2.0.0:

https://semiceu.github.io/GeoDCAT-AP/drafts/2.0.0-draft-0.1/
