### ISSUE TITLE
Define additional terms for spatial resolution in the GeoDCAT-AP namespace?

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/GeoDCAT-AP#15]
> :information_source: Following from background discussion in https://github.com/SEMICeu/GeoDCAT-AP/issues/3

DCAT-AP 2 includes two properties from DCAT 2 to specify spatial and temporal resolution:
- [`dcat:spatialResolutionInMeters`](https://www.w3.org/TR/vocab-dcat-2/#Property:dataset_spatial_resolution)
- [`dcat:temporalResolution`](https://www.w3.org/TR/vocab-dcat-2/#Property:dataset_temporal_resolution)

They will therefore be eventually inherited by the future version of GeoDCAT-AP - ideally, taking into account backward compatibility.

It is worth noting, however, that `dcat:spatialResolutionInMeters` cannot express spatial resolution as equivalent scale, so an option would be defining a specific property in the GeoDCAT-AP namespace.

Based on the DCAT 2 approach, this property could be named

`geodcatap:spatialResolutionAsEquivalentScale`

or, shortly:

`geodcatap:spatialResolutionAsScale`

and take as value an `xsd:decimal` expressing the fraction. E.g.:

````turtle
a:Dataset a dcat:Dataset ;
  geodcatap:spatialResolutionAsScale "0.001"^^xsd:decimal ;
.
````
would state that the spatial resolution of the dataset in equivalent scale is 1:1,000. 

This solution can also be extended to other types of spatial resolution:
- `geodcatap:spatialResolutionAsAngularDistance` or, shortly,  `geodcatap:spatialResolutionInDegrees`
- `geodcatap:spatialResolutionAsVerticalDistanceInMeters` (yes, that's terribly long)

The corresponding tentative definitions:

````turtle
geodcatap:spatialResolutionAsScale a rdf:Property ;
  rdfs:label "spatial resolution as equivalent scale"@en ;
  rdfs:comment """Spatial resolution expressed as equivalent scale, 
    measured by using a representative fraction (e.g., 1:1,000, 1:1,000,000)."""@en ;
  rdfs:range xsd:decimal ;
 .

geodcatap:spatialResolutionInDegrees a rdf:Property ;
  rdfs:label "spatial resolution as angular distance"@en ;
  rdfs:comment """Spatial resolution expressed as angular distance, 
    measured in decimal degrees."""@en ;
  rdfs:range xsd:decimal ;
 .

geodcatap:spatialResolutionAsVerticalDistanceInMeters a rdf:Property ;
  rdfs:label "spatial resolution as vertical distance"@en ;
  rdfs:comment """Spatial resolution expressed as vertical distance, 
    measured in metres."""@en ;
  rdfs:range xsd:decimal ;
 .
````

**Comment by AntoRot** [comment]
The [section 6.13](https://www.w3.org/TR/vocab-dqv/#ExpressDatasetAccuracyPrecision) in the Data Quality Vocabulary (DQV) provides some examples on how `spatialResolutionAsEquivalentScale` and `spatialResolutionAsAngularDistance` can be expressed using the properties defined in that vocabulary.

That approach can be adopted without defining additional properties.  DCAT-AP itself suggests to use DQV for describing spatial precision, accuracy, resolution and other statistics.

**Comment by andrea-perego** [comment]
Thanks, @AntoRot .

Actually, the proposal of using DQV was the original one in https://github.com/SEMICeu/GeoDCAT-AP/issues/3 , where also some possible issues are summarised. Please note, however, that this will still require the definition of new terms.

I'll try to summarise below how to use DQV, so we could better compare it with the idea of extending DCAT2. BTW, for this discussion, it would be worth also looking at https://github.com/w3c/dxwg/issues/84 , which gives the background behind the decision of defining  `dcat:spatialResolutionInMeters`.

As explained in https://github.com/SEMICeu/GeoDCAT-AP/issues/3

> [...] DQV models this information as observations / measurements of a given quality metric (which corresponds to a given type of resolution).
>
> [...]
>
> This would however require the definition of two groups of individuals:
>
> 1. Those corresponding to the different types of resolution (denoting a quality metric).
> 2. Those corresponding to each of the different levels of resolution (denoting the measurement of a specific quality metric).

About the first group, they could be defined (in the GeoDCAT-AP namespace) as follows:

````turtle
:SpatialResolutionAsEquivalentScale a dqv:Metric;
  skos:prefLabel "Spatial resolution as equivalent scale"@en ;
  skos:definition "Spatial resolution expressed as equivalent scale, by using a representative fraction (e.g., 1:1,000, 1:1,000,000)."@en ;
  dqv:expectedDataType xsd:decimal ;
  dqv:inDimension dqv:precision .
    
:SpatialResolutionAsDistance a dqv:Metric;
  skos:prefLabel "Spatial resolution as distance"@en ;
  skos:definition "Spatial resolution expressed as distance."@en ;
  dqv:expectedDataType xsd:decimal ;
  dqv:inDimension dqv:precision .
  
:SpatialResolutionAsHorizontalGroundDistance a dqv:Metric;
  skos:prefLabel "Spatial resolution as horizontal ground distance"@en ;
  skos:definition "Spatial resolution expressed as horizontal ground distance."@en ;
  dqv:expectedDataType xsd:decimal ;
  dqv:inDimension dqv:precision .
    
:SpatialResolutionAsVerticalDistance a dqv:Metric;
  skos:prefLabel "Spatial resolution as vertical distance"@en ;
  skos:definition "Spatial resolution expressed as vertical distance."@en ;
  dqv:expectedDataType xsd:decimal ;
  dqv:inDimension dqv:precision .
    
:SpatialResolutionAsAngularDistance a dqv:Metric;
  skos:prefLabel "Spatial resolution as angular distance"@en ;
  skos:definition "Spatial resolution expressed as angular distance."@en ;
  dqv:expectedDataType xsd:decimal ;
  dqv:inDimension dqv:precision .   
````

The second group of individuals could be instead defined in each metadata record. 

The resulting specification of spatial resolution in a metadata record could be something like:

````turtle
my:dataset a dcat:Dataset;
  dqv:hasQualityMeasurement [ a dqv:QualityMeasurement ;
    dqv:isMeasurementOf :SpatialResolutionAsEquivalentScale ;
    dqv:value "0.000001"^^xsd:decimal 
  ] ;
  .
    
your:dataset a dcat:Dataset;
  dqv:hasQualityMeasurement [ a dqv:QualityMeasurement ;
    dqv:isMeasurementOf :SpatialResolutionAsDistance ;
    dqv:value "1000"^^xsd:decimal ;
    sdmx-attribute:unitMeasure <http://www.wurvoc.org/vocabularies/om-1.8/metre>
  ] ;
  .    
````

So, should we go for DQV or extend DCAT2?

**Comment by AntoRot** [comment]
I continue to prefer the option to use the DQV properties. In both approaches the first group of individuals should be defined anyway altough in a different way, but in case of DQV an existing solution would be reused, although more complex.

On the other side, defining the new properties as extension of DCAT2 would offer a simplest way to express the resolution. 

In any case, as GeoDCAT-AP covers ISO core and INSPIRE metadata, only the corresponding property (i.e. `SpatialResolutionAsEquivalentScale` in addition to `dcat:spatialResolutionInMeters` already available) could be defined.

**Comment by andrea-perego** [comment]
Thanks, @AntoRot .

Actually, although complex, the DQV-based solution provides a common pattern which makes it easier querying metadata compared with having distinct properties for each spatial resolution type. Moreover, it is more sustainable, as it allows a consistent definition of additional types of spatial resolution, if need be. 

There are also a couple of other aspects in favour of DQV:

1. The two approaches are not mutually exclusive, and they could be mapped to each other

3. As you said earlier, @AntoRot , the use of DQV is recommended in DCAT. Moreover, DCAT may eventually extend support for other types of spatial resolution in its next version - see https://github.com/w3c/dxwg/issues/1263 & https://github.com/w3c/dxwg/issues/1266 . So, DQV might be a safer option for the moment

Based on that, I would propose to go for DQV, and consolidate the draft definitions in https://github.com/SEMICeu/GeoDCAT-AP/issues/15#issuecomment-738277249

**Comment by andrea-perego** [comment]
So, trying to consolidate the definitions:

1. Should we merge these two into one?

````turtle
:SpatialResolutionAsDistance a dqv:Metric;
  skos:prefLabel "Spatial resolution as distance"@en ;
  skos:definition "Spatial resolution expressed as distance."@en ;
  dqv:expectedDataType xsd:decimal ;
  dqv:inDimension dqv:precision .
  
:SpatialResolutionAsHorizontalGroundDistance a dqv:Metric;
  skos:prefLabel "Spatial resolution as horizontal ground distance"@en ;
  skos:definition "Spatial resolution expressed as horizontal ground distance."@en ;
  dqv:expectedDataType xsd:decimal ;
  dqv:inDimension dqv:precision .
````

**Comment by AntoRot** [comment]
In ISO 19115 "distance" is simply defined as "ground sample distance", that becomes "horizontal ground sample distance" in ISO 19115-1. This rewording I think was justified in order to distinguish it from the new metadata elements introduced in the latest version of the Standard, i.e. "vertical" and "angularDistance" and consequently the two elements match, also because it was not included as revision in the Annex G.

Consequently, I think that we should merge the two properties.

Concerning the definition of the first group of individuals you proposed in your earlier comment, seen the reasoning made in #23 about keeping properties mapped to elements coming from ISO 19115-1 not covered by the GeoDCAT-AP mappings, no objections to also add the properties corresponding to ISO 19115-1 metadata elements mentioned above, contrary to what I said in the previous comment.

**Comment by andrea-perego** [comment]
Thanks, @AntoRot .

So, maybe we can just extend the first one with some additional textual explanation:

````turtle
:SpatialResolutionAsDistance a dqv:Metric;
  skos:prefLabel "Spatial resolution as distance"@en ;
  skos:definition """Spatial resolution expressed as distance. It corresponds to the notion of spatial resolution as 
    "ground distance" of ISO 19115:2003 and "horizontal ground distance" of ISO 19115-1:2014."""@en ;
  dqv:expectedDataType xsd:decimal ;
  dqv:inDimension dqv:precision .
````

WDYT?

**Comment by andrea-perego** [comment]
Another point:

2. Are you happy with the textual descriptions of these individuals? Is there anything you think should be added / revised?

**Comment by andrea-perego** [comment]
I created a full definition in PR https://github.com/SEMICeu/GeoDCAT-AP/pull/54

Please check it out.

@riccardoAlbertoni , as you are co-editor of DQV, it would be great if you could kindly review this work, and let us know if there's anything wrong and/or to be improved. Thanks!

**Comment by AntoRot** [comment]
@andrea-perego I think that the textual descriptions of both `SpatialResolutionAsDistance` and other individuals are fine.

Thanks.

**Comment by andrea-perego** [comment]
Thanks, @AntoRot .

RDF vocabulary and specification updated via PR https://github.com/SEMICeu/GeoDCAT-AP/pull/54

**PROPOSED RESOLUTION**: Implement these changes in the current draft with the purpose of supporting the DQV approach for spatial resolution in version 2 of GeoDCAT-AP

**Comment by riccardoAlbertoni** [comment]
> I created a full definition in PR #54
> 
> Please check it out.
> 
> @riccardoAlbertoni , as you are co-editor of DQV, it would be great if you could kindly review this work, and let us know if there's anything wrong and/or to be improved. Thanks!

@andrea-perego: Thank you for pointing to me the use of DQV into GeoDCAT-AP. I  have given a quick read to it. The overall approach seems consistent with the DQV; I suggested some very minor changes in the related PR. I might not be fully aware of the whole context, so please feel free to ignore my rephasings if they do not apply to that specific context.

**Comment by andrea-perego** [comment]
Many thanks for your review, @riccardoAlbertoni . Much appreciated.

I applied most of your suggested revisions, and left a comment for other ones, proposing a different revision.

**Comment by riccardoAlbertoni** [comment]
> Many thanks for your review, @riccardoAlbertoni . Much appreciated.
> 
> I applied most of your suggested revisions, and left a comment for other ones, proposing a different revision.

Thanks, it works for me.

**Comment by andrea-perego** [comment]
Revisions applied, and final editorial fixes and revision completed.

With 1 positive vote and no negative vote, the proposed resolution can be considered approved.

I'm going to merge PR https://github.com/SEMICeu/GeoDCAT-AP/pull/54 and close this issue.

@AntoRot , @riccardoAlbertoni , thanks for your contributions.
