### ISSUE TITLE
Specifying spatial / temporal reference systems

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/GeoDCAT-AP#2]
> :information_source:  The possibility of addressing this issue in the scope of the Core Location Vocabulary is discussed in https://github.com/SEMICeu/Core-Location-Vocabulary/issues/2 , from which the following issue description is taken.

For this purpose, GeoDCAT-AP v1.0 uses property `dct:conformsTo`.

Since `dct:conformsTo` is a very general property, the fact that the object is a spatial / temporal reference system is currently addressed by using `dct:type` with the relevant code list values from the INSPIRE Glossary, as shown in the following example:

````
a:Dataset a dcat:Dataset ;
  dct:conformsTo a:SpatialReferenceSystem .
  
a:SpatialReferenceSystem a dct:Standard ;
  dct:type <http://inspire.ec.europa.eu/glossary/SpatialReferenceSystem> .
````

Moreover, [an experimental RDF representation of reference system from the OGC CRS Register](https://joinup.ec.europa.eu/mailman/archives/dcat_application_profile-geo/2016-September/000376.html) has been developed, mapping additional information (as the "name" of the CRS). 

It might be desirable to have a more specific property than `dct:conformsTo` and/or use a stronger typing rather than using `dct:type` with a term from the INSPIRE Glossary.

In such a case, an initial proposal for the definition of specific classes / properties is documented here:

https://joinup.ec.europa.eu/mailman/archives/dcat_application_profile-geo/2015-July/000157.html

> :warning: The Git repository including the the mapping proposal referred to from the mail above has been moved to GitHub: https://github.com/SEMICeu/epsg-to-rdf

Moreover, the new version of the [W3C Time Ontology](https://www.w3.org/TR/owl-time/) includes a class [`time:TRS`](https://www.w3.org/TR/owl-time/#time:TRS) that could be used to type temporal reference systems.

**Comment by andrea-perego** [comment]
DCAT 2 documents the use of `dct:conformsTo` for the specification of coordinate reference systems (see [Example 34](https://www.w3.org/TR/vocab-dcat-2/#ex-dataset-crs)).

Since GeoDCAT-AP uses the same approach, no revision is needed as far as compatibility with DCAT 2 is concerned.

**Comment by bertvannuffelen** [comment]
Applying this approach it indicates that a dataset conforms to a specific CRS. 

However since a dataset is a conceptual thing (a collection of geographical information) and the CRS is usally something very concrete, I expect the CRS be a part of an actual distribution or data service instead of a dataset. 

What is the inituitive meaning of the CRS statement at the level of dataset? Does it mean that all distributions are only be shared according to that CRS? Or is it being collected according that one?

**Comment by andrea-perego** [comment]
Good point, @bertvannuffelen . Actually, this issue was also discussed by the GeoDCAT-AP WG back in 2015, and the agreement was that the CRS could be specified at both the dataset and distribution levels.

About whether the CRS specification makes sense at the dataset level, the point is that this is what happens in INSPIRE / ISO 19115 - i.e., the standards GeoDCAT-AP is based on.

**Comment by andrea-perego** [comment]
This revision has been implemented in the first working draft for GeoDCAT-AP 2.0.0:

https://semiceu.github.io/GeoDCAT-AP/drafts/2.0.0-draft-0.1/

Unless there are any objections, I propose to close this issue.

**Comment by andrea-perego** [comment]
Closing.
