### ISSUE TITLE
Definition of 'Resource' and 'Data Service'

### ISSUE THREAD

**Issue by AntoRot** [SEMICeu/GeoDCAT-AP#22]
In the section _2. Terminology used in the Application Profile_:

- a possible definition of 'Resource' can be that one given in the ISO Standard 19115-1, i.e. "Identifiable asset or means that fulfils a requirement. EXAMPLE: Dataset, dataset series, service, document, initiative, software, person or organization";

- the definition of 'Data Service' can be that one given in DCAT v. 2., i.e. "A collection of operations that provides access to one or more datasets or data processing functions". This definition is very similar to that one of "Spatial Data Service" given in the INSPIRE Directive (Art. 3), i.e. "Spatial Data Services are the operations which may be performed, by invoking a computer application, on the spatial data contained in spatial data sets or on the related metadata".

**Comment by andrea-perego** [comment]
Thanks, @AntoRot .

About the notion of "resource", it is yet to be decided whether it should or not be included. The definition proposed in the EDITOR'S NOTE corresponds to the DCAT2 one.

About data services, the proposed revision is included in pull request https://github.com/SEMICeu/GeoDCAT-AP/pull/26

**Comment by andrea-perego** [comment]
@AntoRot , @bertvannuffelen , following your vote, I will proceed and merge PR https://github.com/SEMICeu/GeoDCAT-AP/pull/26 , and close this issue.

About the option of including a definition of resource, I have created a separate issue: https://github.com/SEMICeu/GeoDCAT-AP/issues/35
