### ISSUE TITLE
Additional properties in GeoDCAT-AP not included in DCAT-AP

### ISSUE THREAD

**Issue by AntoRot** [SEMICeu/GeoDCAT-AP#23]
Some comments concerning some properties added in GeoDCAT-AP but not included in DCAT-AP.

- Section [4.1.3 Optional properties for Catalogue](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#optional-properties-for-catalogue): some properties added correspond to metadata elements not required for discovery services (and in general for network services) in INSPIRE TG, consequently no need to add them in GeoDCAT-AP. Those properties are: ```+reference system```, ```+topic category``` (also in ISO 19115 this metadata element is included in the class MD_**Data**Identification) and ```+theme/category``` (as INSPIRE theme is not required for the services);

- Section [4.2.3 Optional properties for Catalogue Record](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#optional-properties-for-catalogue-record): as Catalogue Record is used to map INSPIRE metadata elements on metadata, only ```+character encoding```, ```+contact point``` and ```+identifier``` should be added. No need to add ```+publisher```, ```+creation date```, ```+creator```, ```+qualified attribution``` and ```+rights holder```;

- Section [4.3.3 Optional properties for Data Service](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#optional-properties-for-data-service): for the same reasons above, the properties ```+topic category``` and ```+theme/category``` shouldn't be added for Data Service;

- Section [4.3.3 Optional properties for Data Service](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#optional-properties-for-data-service): in ISO 19115 spatial resolution is a specific metadata element only for dataset. In INSPIRE TG the requirement is indeed that for services the spatial resolution shall be expressed using the ```gmd:abstract``` element. For this reason, the properties ```+spatial resolution``` and ```+spatial resolution as equivalent scale, angular distance, vertical distance``` shouldn't be added;

- Section [4.3.3 Optional properties for Data Service](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#optional-properties-for-data-service): in ISO 19115 language is a specific metadata element only for dataset as well, consequently the property ```+language``` shouldn't be added;

- Section 4.7.2 [Optional properties for Category Scheme](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#optional-properties-for-category-scheme): generally the publication date of the vocabulary/thesaurus is required in INSPIRE TG. In a similar way, only the property ```+release date``` could be added;

- Section [5.2 Controlled vocabularies to be used](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#controlled-vocabularies-to-be-used): update the table according to what above if the proposals will be accepted.

**Comment by andrea-perego** [comment]
Thanks for raising this issue, @AntoRot .

These properties were already supported as optional in the first version of GeoDCAT-AP, and in the defined mappings, although it may be not so visible in the specification. The rationale was to be inclusive, and support possibly relevant metadata elements, even if not required in INSPIRE and/or ISO 19115.

If this approach needs to be changed in the new version of GeoDCAT-AP, backward compatibility should be taken into account. So, it would be probably safer to proceed stepwise, by dropping first only those properties that are not actually supported by INSPIRE and ISO 19115 in a given context (class).

@AntoRot , may I ask which of the properties you mention in your comment fit with this criterion?

**Comment by AntoRot** [comment]
> So, it would be probably safer to proceed stepwise, by dropping first only those properties that are not actually supported by INSPIRE and ISO 19115 in a given context (class).

>@AntoRot , may I ask which of the properties you mention in your comment fit with this criterion?

Below the properties that fit with the criterion quoted above:

- ```topic category``` is not supported either by INSPIRE and by ISO 19115 for the services, consequently it shouldn't be added in the classes ```dcat:Catalog``` and ```dcat:DataService```. In the first version of GeoDCAT-AP it was only included in the class ```dcat:Dataset```. 

- what above is also applicable for ```spatial resolution``` and ```language``` supported by ISO 19115 and INSPIRE only for datasets and dataset series.

To be noted however that in ISO 19115-1 the elements ```topic category``` and  ```spatial resolution``` are supported both for datasets and for services, but that standard doesn't fall under the scope of GeoDCAT-AP.

**Comment by andrea-perego** [comment]
Thanks, @AntoRot .

About this point:

> To be noted however that in ISO 19115-1 the elements `topic category` and `spatial resolution` are supported both for datasets and for services, but that standard doesn't fall under the scope of GeoDCAT-AP.

So, probably it is worth keeping them in the GeoDCAT-AP vocabulary description, as done in the current draft (for possible use in GeoDCAT-AP records created directly in RDF). 

ISO 19115-1 is indeed not covered by the GeoDCAT-AP mappings. However, support may be added in the future, and then we should have to re-include these metadata elements. 

Do you see any issue in this approach?

**Comment by AntoRot** [comment]
@andrea-perego,

the approach proposed makes sense. 

Thanks.

**Comment by andrea-perego** [comment]
Thanks, @AntoRot .

Unless there are any objections, I propose to close this issue.

**Comment by AntoRot** [comment]
@andrea-perego,

no objection from my side.

Thanks.

**Comment by andrea-perego** [comment]
Closing.
