### ISSUE TITLE
Limitations on public access - Revision of the example

### ISSUE THREAD

**Issue by AntoRot** [SEMICeu/GeoDCAT-AP#25]
INSPIRE TG Requirement C.17 states that limitations on public access (or lack of such limitations) shall be described using a combination of one instance of gmd:accessConstraints/gmd:MD_RestrictionCode element with code list value "otherRestrictions" and at least one instance of **gmd:otherConstraints/gmx:Anchor** pointing to one of the values from the code list for [LimitationsOnPublicAccess](https://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess).
The first part of the example (i.e. Resource metadata in ISO 19139) provided in the section [B.6.15 Conditions for access and use and limitations on public access – Use limitation and access / other constraints](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#conditions-for-access-and-use-and-limitations-on-public-access-use-limitation-and-access-other-constraints) is not consistent with the requirement mentioned above, as free text is not allowed for describing the limitations on public access. Consequently, the example should be revised as follows:

Resource metadata in ISO 19139:

```xml
<gmd:MD_Metadata>
  ...
  <gmd:MD_LegalConstraints>
    <gmd:useConstraints>
      <gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions"/>
    </gmd:useConstraints>
    <gmd:otherConstraints>
      <gco:CharacterString>
        The dataset contains parts which are restricted 
        by the data providers and not to be made public. 
        For further information and specification regarding 
        the use limitations and constraints please consult 
        the file WISE_WFD_ReferenceSpatialDataSets_2020-04-02.pdf 
        which is provided together with the data.    
      </gco:CharacterString>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
  ...
  <gmd:MD_LegalConstraints>
    <gmd:accessConstraints>
      <gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions"/>
    </gmd:accessConstraints>
    <gmd:otherConstraints>
<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1b">public access limited according to Article 13(1)(b) of the INSPIRE Directive</gmx:Anchor>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
  ...
</gmd:MD_Metadata>
```

and consequently 

Resource metadata in GeoDCAT-AP:

```turtle
[] dcat:distribution [ a dcat:Distribution ;
  dct:license [ a dct:LicenseDocument ;
    rdfs:label """
        The dataset contains parts which are restricted 
        by the data providers and not to be made public. 
        For further information and specification regarding 
        the use limitations and constraints please consult 
        the file WISE_WFD_ReferenceSpatialDataSets_2020-04-02.pdf 
        which is provided together with the data.    
      """@en ] ;
  dct:accessRights <http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1b> ; 
] .
```

**Comment by andrea-perego** [comment]
Thanks for raising this issue, @AntoRot .

An option would be to drop support for the use of free-text for the specification of access limitations, and require the use of URIs only. However, this may have an impact in metadata records not yet aligned with the requirements of the INSPIRE MD TG or other ISO 19115 records, as it will result in information loss.

I would propose we keep the examples as they are, but highlight the recommendation of the INSPIRE MD TG on the specification of access limitations, stating also that the use of free-text is allowed only for legacy metadata records not yet compliant with the latest version of the INSPIRE MD TG.

The proposed revision is implemented in the following pull request: https://github.com/SEMICeu/GeoDCAT-AP/pull/28

Do you think this solution is acceptable?

**Comment by AntoRot** [comment]
Thanks @andrea-perego.

Your proposal sounds fine to me.

**Comment by andrea-perego** [comment]
Revision implemented in the editor's draft in view of the publication of the 2nd working draft:

https://semiceu.github.io/GeoDCAT-AP/drafts/latest/
