### ISSUE TITLE
Add definition of Resource in §2

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/GeoDCAT-AP#35]
<p>It is to be decided whether a definition of Resource (in the sense of <code>dcat:Resource</code>) should be included.</p>

<p>The proposed definition is the DCAT2 one:</p>

<blockquote>
<p>A <strong>Resource</strong> is a dataset, data service, or any other kind of resource documented in a catalogue.</p>
</blockquote>

<p>Having such definition (even though class <code>dcat:Resource</code> will not explicitly included) would help scope references to this notion inside class and property descriptions. Without it, <em>resource</em> may be intended not as "any type of resource documented in a catalogue" but in its far broader RDF sense - i.e., "All things described by RDF are called resources, and are instances of the class <code>rdfs:Resource</code>. This is the class of everything." <a href="https://www.w3.org/TR/rdf-schema/#ch_resource">[RDF-SCHEMA], §2.1</a>.</p>

<p>If such definition will be included, it would be desirable that future versions of DCAT-AP be aligned accordingly.</p>

**Comment by akuckartz** [comment]
Please do not use the term "Resource" in a different sense than the "Resource" in Resource Description Framework (RDF). Maybe something like "DCAT-Resource"?

**Comment by AntoRot** [comment]
I think that a solution can be either adopting a similar editorial form used in DCAT2 [section 5.1](https://www.w3.org/TR/vocab-dcat-2/#dcat-scope) (i.e. URI and definition) or specifying the URI only for the Resource that can be confused with ```rdfs:Resource```, i.e. "A Resource (dcat:Resource) is a dataset, data service, or any other kind of resource documented in a catalogue".

**Comment by andrea-perego** [comment]
Thanks, @akuckartz & @AntoRot .

We have actually tried to address your concerns in PR https://github.com/SEMICeu/GeoDCAT-AP/pull/42 , while working on issue https://github.com/SEMICeu/GeoDCAT-AP/issues/36 .

Quoting from https://github.com/SEMICeu/GeoDCAT-AP/issues/36#issuecomment-738273896 :

> Revisions have been made by listing, when necessary, the different classes / resource types to which a class / property description refers.
>
> The term "resource" was never used in the narrow sense of `dcat:Resource` without a proper qualification, and always complemented with the list of relevant resource types - e.g., "a resource documented in a Catalogue (as a Data Service, Dataset, or another Catalogue)".

With these changes, the inclusion of a definition for `dcat:Resource` is not necessary for being used in class and property definitions.

I'm therefore closing this issue and the related PR https://github.com/SEMICeu/GeoDCAT-AP/pull/37
