### ISSUE TITLE
Defining an XML / RDF datatype for GeoJSON

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/GeoDCAT-AP#4]
Although RDF datatypes exist for WKT and GML (they are defined in GeoSPARQL), an XML / RDF datatype for GeoJSON is missing.

To address this issue, GeoDCAT-AP v1.0 uses the URL of the corresponding IANA media type (namely [`http://www.iana.org/assignments/media-types/application/geo+json`](https://www.iana.org/assignments/media-types/application/geo+json)), but this solution is not optimal, and the definition of a specific datatype might be considered. In such a case, the question is whether this should be done in the framework of GeoDCAT-AP or of the Core Location Vocabulary.

About this issue, see also https://github.com/SEMICeu/Core-Location-Vocabulary/issues/2

**Comment by akuckartz** [comment]
I am not sure if that is relevant here, but there is some hope that JSON-LD 1.1 can be a basis for GeoJSON-LD.

**Comment by bertvannuffelen** [comment]
Also note there are now 2 versions of geoJSON. Can these serializations be distinguished?

**Comment by dr-shorthair** [comment]
Also see https://w3c.github.io/json-ld-syntax/#the-rdf-json-datatype

**Comment by andrea-perego** [comment]
@akuckartz said:

> I am not sure if that is relevant here, but there is some hope that JSON-LD 1.1 can be a basis for GeoJSON-LD.

Thanks for the heads-up . This could be an additional geometry encoding to be supported. 

However, I think it should be kept separate from a "plain" GeoJSON literal encoding, for which the GeoDCAT-AP WG had some use cases in mind.

**Comment by andrea-perego** [comment]
@bertvannuffelen said:

> Also note there are now 2 versions of geoJSON. Can these serializations be distinguished?

This is just my personal view, but I think the reference one should be the latest - i.e., the one standardised in RFC 7946 (https://tools.ietf.org/html/rfc7946) - which supersedes the original one, and it is already being supported in widely used tools (as PostGIS). 

Said that, there's a possible issue in the IETF version of GeoJSON, as pointed out in https://github.com/SEMICeu/GeoDCAT-AP/issues/6, but IMO it can be sorted out.

**Comment by andrea-perego** [comment]
@dr-shorthair said:

> Also see https://w3c.github.io/json-ld-syntax/#the-rdf-json-datatype

Thanks for the pointer. This would indeed fit better than the GeoJSON media type URI. However, I wonder whether there may be some possible issues on using the `rdf:JSON` datatype for GeoJSON literals, since there exist other JSON-based geometry encodings - as the ones used in ArcGIS (https://developers.arcgis.com/documentation/common-data-types/geometry-objects.htm).

**Comment by andrea-perego** [comment]
Noting there's work under way in the new version of GeoSPARQL - see:
- https://github.com/opengeospatial/ogc-geosparql/issues/1 
- https://github.com/opengeospatial/ogc-geosparql/pull/48

The [current proposal](https://github.com/situx/ogc-geosparql/blob/master/1.1/geo.ttl#L174) defines the GeoJSON literal datatype as follows:

````turtle
@prefix : <http://www.opengis.net/ont/geosparql#> .

:geoJSONLiteral a rdfs:Datatype ;
	dc:contributor "Timo Homburg" ;
	dc:creator "OGC GeoSPARQL 2.0 Standard Working Group" ;
	dc:date "2020-10-30"^^xsd:date ;
	dc:description """
      A GeoJSON serialization of a geometry object.
    """@en ;
	rdfs:comment """
      A GeoJSON serialization of a geometry object.
    """@en ;
	rdfs:seeAlso <https://tools.ietf.org/html/rfc7946> .
	rdfs:isDefinedBy <http://www.opengis.net/ont/geosparql> , <http://www.opengis.net/spec/geosparql/1.1> ;
	rdfs:label "GeoJSON Literal"@en ;
	skos:definition """
      A GeoJSON serialization of a geometry object.
    """@en ;
	skos:prefLabel "GeoJSON Literal"@en .
````

See also [the relevant section in the GeoSPARQL 1.1 draft](https://github.com/situx/ogc-geosparql/blob/master/1.1/spec/11-Part-08.adoc#requirements-for-geojson-serialization-serializationgeojson) (pull request approved, but not yet merged).

**Comment by andrea-perego** [comment]
> Noting there's work under way in the new version of GeoSPARQL - see:
> 
> * [opengeospatial/ogc-geosparql#1](https://github.com/opengeospatial/ogc-geosparql/issues/1)
> * [opengeospatial/ogc-geosparql#48](https://github.com/opengeospatial/ogc-geosparql/pull/48)

PR https://github.com/opengeospatial/ogc-geosparql/pull/48 has been eventually merged.

Should we already adopt this solution, or wait until the new version of GeoSPARQL is officially out?

**Comment by andrea-perego** [comment]
Please give your feedback on the following proposal:

**PROPOSED RESOLUTION**: Adopt in GeoDCAT-AP 2 the GeoJSON datatype defined in the current draft of the new version of GeoSPARQL, and deprecate the use of the GeoJSON media type URI for GeoJSON literals supported so far in GeoDCAT-AP.

**Comment by andrea-perego** [comment]
@akuckartz , do you have any concern on the proposal?

**Comment by akuckartz** [comment]
No, I only marked the comment to signal that I "should" perhaps look at this closer ;-) I do not know if I like GeoJSON.

**Comment by AntoRot** [comment]
@andrea-perego 
I'd agree with your proposed resolution, but we should take into account that the IANA URI for GeoJSON literals is still used e.g. in [CKAN](https://github.com/ckan/ckanext-dcat#rdf-dcat-to-ckan-dataset-mapping) for the `dct:spatial` property expressed as geometry.

Consequently, deprecating the use of the GeoJSON media type URI for GeoJSON literals will affect the compability with the CKAN model for all data providers who use that tool. Unless CKAN community will align the RDF DCAT to CKAN mapping by including the new GeoJSON datatype being adopted in GeoDCAT-AP 2.0.

**Comment by andrea-perego** [comment]
Thanks for raising this issue, @AntoRot .

For the GeoJSON datatype we could follow the same approach used for deprecated classes and properties, i.e., although they are replaced by other ones, they will still be supported for backward compatibility. Such support could be phased out in future versions of GeoDCAT-AP,  if this can be done safely.

Moreover, we can take an action, and report this revision to the CKAN community.

Would this be enough to address this issue?

**Comment by andrea-perego** [comment]
I have create a draft PR along these lines: https://github.com/SEMICeu/GeoDCAT-AP/pull/58

The main changes concern [§B.6.10](https://raw.githack.com/SEMICeu/GeoDCAT-AP/fix-issue-4/drafts/latest/index.html#geographic-bounding-box---geographic-location-of-the-dataset-by-4-coordinates-or-by-geographic-identifier) and [§B.6.10.1](https://raw.githack.com/SEMICeu/GeoDCAT-AP/fix-issue-4/drafts/latest/index.html#bounding-box).

In particular:

The following text has been added to the NOTE at the beginning of [§B.6.10](https://raw.githack.com/SEMICeu/GeoDCAT-AP/fix-issue-4/drafts/latest/index.html#geographic-bounding-box---geographic-location-of-the-dataset-by-4-coordinates-or-by-geographic-identifier):

> - For GeoJSON [RFC7946] literals, the GeoJSON IANA media type URI used until [GeoDCAT-AP-20160802] is replaced by datatype gsp:geoJSONLiteral, defined in the current draft of the new version of GeoSPARQL [GeoSPARQL11].

The following text has been added at the end of [§B.6.10.1](https://raw.githack.com/SEMICeu/GeoDCAT-AP/fix-issue-4/drafts/latest/index.html#bounding-box), right before [Example 35](https://raw.githack.com/SEMICeu/GeoDCAT-AP/fix-issue-4/drafts/latest/index.html#ex-mapping-geo-bbox):

> As geometries may be provided in multiple encodings, the corresponding datatype SHOULD be always specified to ensure that the geometry literal is correctly interpreted.
>
> For GML and WKT, the [GeoSPARQL] datatypes gsp:gmlLiteral and gsp:wktLiteral, respectively, MUST be used.
>
>For GeoJSON [RFC7946], datatype gsp:geoJSONLiteral, defined in the current draft of the new version of GeoSPARQL [GeoSPARQL11], SHOULD be used.
>
>For the other geometry encodings, no datatype is currently available. Therefore, their interoperability is not ensured.
>
> NOTE
> Until [GeoDCAT-AP-20160802], the recommended solution to specify the datatype for GeoJSON literals was to use the following URI from the IANA Media Types registry [IANA-MEDIA-TYPES]:
>
> https://www.iana.org/assignments/media-types/application/vnd.geo+json
>
> This solution, intentionally meant to be provisional (see Issue #4), is deprecated starting from this version of GeoDCAT-AP in favour of gsp:geoJSONLiteral. It will still be supported for backward compatibility with legacy metadata and applications, but it may be phased out in future versions of GeoDCAT-AP.

Would this work?

**Comment by andrea-perego** [comment]
Thanks, @AntoRot .

Unless there are any objections, I will merge PR https://github.com/SEMICeu/GeoDCAT-AP/pull/58 and close this issue.

**Comment by AntoRot** [comment]
No objections from my side. Thanks.
