### ISSUE TITLE
Specifying start / end date(time) for temporal coverage

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/GeoDCAT-AP#5]
> :information_source: Copy-pasted from https://github.com/SEMICeu/Core-Location-Vocabulary/issues/2

Currently, this information is specified in DCAT-AP by using `schema:startDate` and `schema:endDate`, respectively, following [ADMS](https://www.w3.org/TR/vocab-adms/#period-of-time). GeoDCAT-AP v1.0 follows the same approach.

This issue has been brought to the attention of the W3C Dataset Exchange Working Group (see [UC27](https://www.w3.org/TR/dcat-ucr/#ID27)), so a possible solution might be contributed in that context.

**Comment by andrea-perego** [comment]
DCAT 2 defines 2 specific properties for this purpose - namely, [`dcat:startDate`](https://www.w3.org/TR/vocab-dcat-2/#Property:period_start_date) and [`dcat:endDate`](https://www.w3.org/TR/vocab-dcat-2/#Property:period_end_date). Moreover, it indicates the use of properties `time:hasBeginning` and `time:hasEnd` from [[OWL-Time](https://www.w3.org/TR/owl-time/)] for periods of time not specified with the Gregorian calendar.

DCAT-AP 2 has adopted these properties (see https://github.com/SEMICeu/DCAT-AP/issues/83 & https://github.com/SEMICeu/DCAT-AP/issues/84), so they should be inherited by GeoDCAT-AP, possibly taking into account backward interoperability (e.g., by marking `schema:startDate` and `schema:endDate` as deprecated).

**Comment by akuckartz** [comment]
> (e.g., by marking dcat:startDate and dcat:endDate as deprecated)

I think you meant deprecating schema:startDate and schema:endDate.

**Comment by andrea-perego** [comment]
@akuckartz said:

> > (e.g., by marking dcat:startDate and dcat:endDate as deprecated)
> 
> I think you meant deprecating schema:startDate and schema:endDate.

Indeed. Thanks for the correction.

**Comment by andrea-perego** [comment]
This revision has been implemented in the first working draft for GeoDCAT-AP 2.0.0:

https://semiceu.github.io/GeoDCAT-AP/drafts/2.0.0-draft-0.1/
