### ISSUE TITLE
Spatial representation type code list

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/GeoDCAT-AP#55]
This code list has not yet been added to the INSPIRE Registry.

To be decided if any action should be taken.

**Comment by AntoRot** [comment]
As in #56, we could propose to the [INSPIRE Registry control body](https://github.com/INSPIRE-MIF/helpdesk-registry) to publish the code list and the update GeoDCAT-AP with the related URI.

**Comment by andrea-perego** [comment]
@AntoRot said:

> As in #56, we could propose to the [INSPIRE Registry control body](https://github.com/INSPIRE-MIF/helpdesk-registry) to publish the code list and the update GeoDCAT-AP with the related URI.

Request submitted: https://github.com/INSPIRE-MIF/helpdesk-registry/issues/9

**Comment by andrea-perego** [comment]
The spatial representation type code list is now available from the INSPIRE Registry - see https://github.com/INSPIRE-MIF/helpdesk-registry/issues/9#issuecomment-815489521

**Comment by andrea-perego** [comment]
GeoDCAT-AP XSLT revised accordingly - see https://github.com/SEMICeu/iso-19139-to-dcat-ap/issues/28

**Comment by andrea-perego** [comment]
GeoDCAT-AP specification updated accordingly.

Closing this issue.
