### ISSUE TITLE
Maintenance frequency code list

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/GeoDCAT-AP#56]
This code list has not yet been added to the INSPIRE Registry.

To be decided if any action should be taken.

**Comment by AntoRot** [comment]
As that code list wasn't published in the INSPIRE Registry, we published it in the [Italian Registry](https://registry.geodati.gov.it/metadata-codelist/maintenanceFrequency). We also published the [cross-map register](https://registry.geodati.gov.it/cross-map-frequency) with the mapping between the ISO code list and the EU Vocabularies Frequency Named Authority List based on the alignment defined in GeoDCAT-AP, following the requirements of ISO Standard 19146 (Geographic information — Cross-domain vocabularies).

We could propose to the [INSPIRE Registry control body](https://github.com/INSPIRE-MIF/helpdesk-registry) to publish the code list and then update the [related section](https://semiceu.github.io/GeoDCAT-AP/drafts/latest/#maintenance-information---not-in-iso19115-core) in GeoDCAT-AP with the URI coming from that Registry.

An alternative option would be to map the two values from ISO code list not covered by the EU Vocabularies Frequency Named Authority List (i.e. `asNeeded` and `notPlanned)` to the EUV-FREQ value `OTHER.`

**Comment by andrea-perego** [comment]
@AntoRot said:

> As that code list wasn't published in the INSPIRE Registry, we published it in the [Italian Registry](https://registry.geodati.gov.it/metadata-codelist/maintenanceFrequency). We also published the [cross-map register](https://registry.geodati.gov.it/cross-map-frequency) with the mapping between the ISO code list and the EU Vocabularies Frequency Named Authority List based on the alignment defined in GeoDCAT-AP, following the requirements of ISO Standard 19146 (Geographic information — Cross-domain vocabularies).
> 
> We could propose to the [INSPIRE Registry control body](https://github.com/INSPIRE-MIF/helpdesk-registry) to publish the code list and then update the [related section](https://semiceu.github.io/GeoDCAT-AP/drafts/latest/#maintenance-information---not-in-iso19115-core) in GeoDCAT-AP with the URI coming from that Registry.

Request submitted: https://github.com/INSPIRE-MIF/helpdesk-registry/issues/9

**Comment by andrea-perego** [comment]
The maintenance frequency code list is now available from the INSPIRE Registry - see https://github.com/INSPIRE-MIF/helpdesk-registry/issues/9#issuecomment-815489521

**Comment by andrea-perego** [comment]
GeoDCAT-AP XSLT revised accordingly - see https://github.com/SEMICeu/iso-19139-to-dcat-ap/issues/28

**Comment by andrea-perego** [comment]
GeoDCAT-AP specification updated accordingly.

A possible additional action is to investigate if `asNeeded` and `notPlanned` might be included in the EU Vocabularies Frequency NAL.

**Comment by jakubklimek** [comment]
I have sent a proposal to add the two terms to the [EU Vocabularies Frequency NAL](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/frequency) to support more precise alignment with the [Maintenance frequency](https://inspire.ec.europa.eu/metadata-codelist/MaintenanceFrequency) code list. I will update this issue according to the response I get.

**Comment by jakubklimek** [comment]
Response from the Publications Office is that they will investigate the suggestion in the process of the revision for the next release (no timeline provided).

**Comment by jakubklimek** [comment]
The word from the Publications Office is that the two conepts will be included in the [NAL](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/frequency)(probably in June 2024). The mapping will be adjusted accordingly.

**Comment by jakubklimek** [comment]
The items were added as:
http://publications.europa.eu/resource/authority/frequency/AS_NEEDED
http://publications.europa.eu/resource/authority/frequency/NOT_PLANNED
