### ISSUE TITLE
dataset.ttl missing type dctLocation?

### ISSUE THREAD

**Issue by alko-k** [SEMICeu/GeoDCAT-AP#61]
In this example: https://github.com/SEMICeu/GeoDCAT-AP/blob/gh-pages/releases/examples/dataset.ttl

in the following property, I think you are missing that it is dct:Location

dct:spatial [ dcat:bbox "<gml:Envelope srsName=\"http://www.opengis.net/def/crs/OGC/1.3/CRS84\"><gml:lowerCorner>-31.285 27.642</gml:lowerCorner><gml:upperCorner>34.099 70.075</gml:upperCorner></gml:Envelope>"^^gsp:gmlLiteral,
        "POLYGON((-31.285 70.075,34.099 70.075,34.099 27.642,-31.285 27.642,-31.285 70.075))"^^gsp:wktLiteral ] ;

**Comment by andrea-perego** [comment]
Thanks for pointing this out, @alko-k .

This issue will be addressed via PR https://github.com/SEMICeu/GeoDCAT-AP/pull/62

**Comment by andrea-perego** [comment]
PR https://github.com/SEMICeu/GeoDCAT-AP/pull/62 has been merged.

Closing this issue.
