### ISSUE TITLE
ISO 19115:2003 "HAS BEEN REVISED BY ISO 19115-1:2014"

### ISSUE THREAD

**Issue by akuckartz** [SEMICeu/GeoDCAT-AP#63]
References to ISO 19115:2003 should be replaced by references to ISO 19115-1:2014:
https://www.iso.org/standard/26020.html

**Comment by andrea-perego** [comment]
@akuckartz , the point is that the mappings defined in GeoDCAT-AP concern ISO 19115:2003 - quoting from [the introduction](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#introduction):

> GeoDCAT-AP provides an RDF vocabulary and the corresponding RDF syntax binding for the union of metadata elements of the core profile of ISO 19115:2003 [ISO-19115] and those defined in the framework of the INSPIRE Directive [INSPIRE-DIR].

The definition of mappings for ISO 10115-1:2014 may be part of future work, and a preliminary analysis is included in appendix to the GeoDCAT-AP specification - see [§B.7  Comparison between INSPIRE and ISO 19115-1:2014](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#comparison-between-inspire-and-iso19115-12014).

**Comment by andrea-perego** [comment]
@akuckartz , unless you have any further comments, I will close this issue.

**Comment by andrea-perego** [comment]
Closing.
