### ISSUE TITLE
Question on automation of the index.html docmentation

### ISSUE THREAD

**Issue by JohannesLipp** [SEMICeu/GeoDCAT-AP#66]
Dear @andrea-perego and team,

we found the GeoDCAT-AP in this repository and enjoyed it.

As we are also developing a DCAT-AP (called [napDCAT-AP](https://napcore.eu/providing-a-baseline-for-a-new-metadata-scheme-for-european-naps/)) for [our project NAPCORE](https://napcore.eu/) on National Access Points, we have a technical question to you: Did you manually create [the index.html file](https://github.com/SEMICeu/GeoDCAT-AP/blob/gh-pages/releases/2.0.0/index.html) for [the ReSpec documentation page](https://semiceu.github.io/GeoDCAT-AP/releases/) or did you use any automation? In case of the latter, it would be great if you share these automation scripts with us so that we can build on these. 

Thank you so much in advance! Best,
Johannes

**Comment by bertvannuffelen** [comment]
@JohannesLipp

there are 2 approaches here: the one used here in GeoDCAT-AP and the one used by the other SEMIC specifications. 
The first is a setup that @andrea-perego can explain.

The second I can provide you with assistance how it works. It also can support the Respec look and feel, if your prefer that one. 

kr,

Bert

**Comment by andrea-perego** [comment]
Thanks, @JohannesLipp . I'm happy you like it :)

To come to your question, the specification is created manually, although some sections (as the summary tables in [Appendix A](https://semiceu.github.io/GeoDCAT-AP/drafts/latest/#quick-reference-of-classes-and-properties)) are automatically generated via the scripts in folder https://github.com/SEMICeu/GeoDCAT-AP/tree/gh-pages/drafts/latest/scripts

This applies only to [the editor's draft of GeoDCAT-AP](https://semiceu.github.io/GeoDCAT-AP/drafts/latest/). The versions under the ["releases"](https://github.com/SEMICeu/GeoDCAT-AP/tree/gh-pages/releases) folder, are instead created from the editor's draft by using the [ReSpec export functionality](https://respec.org/docs/#static-snapshots) (that you can activate by clicking on the "ReSpec" button on the top-right corner of the editor's draft page).

Anyway, in case your purpose is to automatically generate the documentation from the formal definition of the application profile, there are some tools for this - as the SHACL Play! API: https://shacl-play.sparna.fr/play/doc

@bertvannuffelen , any other suggestion?

**Comment by jakubklimek** [comment]
@JohannesLipp For the second approach mentioned by @bertvannuffelen, please also see the [SEMIC toolchain manual](https://github.com/SEMICeu/toolchain-manual).

Closing as this issue is unrelated to the contents of GeoDCAT-AP.
