### ISSUE TITLE
GeoDCAT-AP update for DCAT-AP 3.0

### ISSUE THREAD

**Issue by daniwelter** [SEMICeu/GeoDCAT-AP#67]
Dear GeoDCAT-AP team,

I know DCAT-AP 3.0 has only been out a couple of days but are there any plans to align GeoDCAT-AP with the new version of DCAT-AP (and by extension, DCAT-3)? And if so, what would roughly be the timeframe?

I'm working on a cataloguing project focussing on environmental datasets. Our principal reference model is DCAT-AP in order to be compatible with various national and European data catalogues, but we also require the specific scope of GeoDCAT-AP to align with INSPIRE-related requirements for some datasets. We have several use cases for the new `DatasetSeries` in DCAT-AP and would welcome being able to remain fully compatible with both profiles.

**Comment by andrea-perego** [comment]
@daniwelter , work on aligning GeoDCAT-AP with DCAT-AP 3 is now underway:

https://github.com/SEMICeu/GeoDCAT-AP/labels/release%3A3.0.0

**Comment by jakubklimek** [comment]
@daniwelter the GeoDCAT-AP revision timeline will be announced on the [introductory webinar](https://joinup.ec.europa.eu/collection/semic-support-centre/event/introductory-webinar-revision-geodcat-ap), feel free to join.

**Comment by jakubklimek** [comment]
As this is not an actual GeoDCAT-AP issue, and the revision is underway, I am closing this. The progress on DatasetSeries can be monitored in #71 and #72
