### ISSUE TITLE
Alignment with version 2.2.0 of the INSPIRE Metadata Technical Guidelines

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/GeoDCAT-AP#70]
This issue is meant to provide a checklist of the revisions needed to align GeoDCAT-AP with the INSPIRE Metadata Technical Guidelines, version 2.1.3: 

https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/

Related issues:
- [ ] https://github.com/SEMICeu/GeoDCAT-AP/issues/72

**Comment by jakubklimek** [comment]
The current version of the Technical Guidelines as of `2024-01-31` is 2.2.0.

**Comment by jakubklimek** [comment]
No needed revisions identified.
