### ISSUE TITLE
Add class dcat:DatasetSeries

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/GeoDCAT-AP#71]
**Problem statement**

Following DCAT 3. DCAT-AP 3 introduces a new class `dcat:DatasetSeries`.

This class corresponds to the ISO 19115 / INSPIRE notion of "data set series":

https://inspire.ec.europa.eu/glossary/DataSetSeries

Until GeoDCAT-AP 2, dataset series were typed (`rdf:type`) as `dcat:Dataset`'s. 

For more details, see the GeoDCAT-AP 2 specification (in particular, [§B.6.3](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#resource-type---not-in-iso19115-core)).

**Proposal**

To be aligned with DCAT-AP 3 and DCAT 3, GeoDCAT-AP 3 should deprecate the use of class `dcat:Dataset` for dataset series, and replace it with class `dcat:DatasetSeries`.

**Comment by jakubklimek** [comment]
dcat:DatasetSeries will be included as part of DCAT-AP 3.0.0 alignment.
