### ISSUE TITLE
Properties for class dcat:DatasetSeries

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/GeoDCAT-AP#72]
> ℹ️ Parent issue: https://github.com/SEMICeu/GeoDCAT-AP/issues/71

**Problem statement**

Properties for class `dcat:DatasetSeries` should comply with both DCAT-AP 3 and the INSPIRE Metadata Regulation and Technical Guidelines.

DCAT-AP 3 supports a specific set of properties for dataset series, consisting of a subset of those of datasets, plus some specific to dataset series (see the DCAT-AP 3 specification, [§7.9](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#DatasetSeries)).

On the other hand, in INSPIRE, datasets and dataset series share the same set of metadata elements - see the Annex to the INSPIRE Metadata Regulation ([Part C](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02008R1205-20081224&qid=1706741391819#tocId13)), and the INSPIRE Metadata Technical Guidelines ([§C.2](https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/metadata-iso19139.html#_inspire_implementing_rules_for_metadata_regulation_12052008)).

**Proposal** 

To be aligned with DCAT-AP 3, DCAT 3, and the INSPIRE Regulation and Technical Guidelines, in GeoDCAT-AP 3 the properties of class `dcat:DatasetSeries` should correspond to the union of:
- the properties associated with class `dcat:Dataset` in GeoDCAT-AP 3, and
- the properties supported for class `dcat:DatasetSeries` in DCAT-AP 3.

**Comment by LenkaRejentova** [comment]
We prefer to have complete information for a series as for a dataset, as it is in INSPIRE and ISO.
