### ISSUE TITLE
Add versioning properties

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/GeoDCAT-AP#73]
**Problem statement**

Following DCAT 3, DCAT-AP 3 introduces a set of versioning properties, replacing the corresponding ones in earlier versions of DCAT-AP (see the DCAT-AP 3 specification, [§A.1](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#deprecated-properties-and-classes)).

In particular:
- [`dcat:hasVersion`](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.hasversion) replaces `dct:hasVersion` (deprecated).
- [`dcat:isVersionOf`](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.isversionof) replaces `dct:isVersionOf` (deprecated).
- [`dcat:version`](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.version) replaces `owl:versionInfo` (deprecated).

**Proposal**

To be aligned with DCAT-AP 3 and DCAT 3, GeoDCAT-AP 3 should deprecate the use of `dct:hasVersion`, `dct:isVersionOf`, and `owl:versionInfo`, and replace them with `dcat:hasVersion`, `dcat:isVersionOf`, and `dcat:version`, respectively.

**Comment by jakubklimek** [comment]
`dcat:hasVersion` and `dcat:version` were added. `dcat:isVersionOf` was removed due to #90
