### ISSUE TITLE
Add properties for datasets in a dataset series

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/GeoDCAT-AP#75]
**Problem statement**

Following DCAT 3, DCAT-AP 3 introduces properties specific to datasets in a dataset series, namely, `dcat:inSeries`, `dcat:next`, and `dcat:prev` (see the DCAT-AP 3 specification, [§7.8](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#DatasetmemberofaDatasetSeries)).
d).

**Proposal**

To be aligned with DCAT-AP 3 and DCAT 3, GeoDCAT-AP 3 should include properties  `dcat:inSeries`, `dcat:next`, and `dcat:prev` .

**Comment by jakubklimek** [comment]
Dataset in Dataset Series did not make it into the current and final draft of DCAT-AP 3.0.0.
Still, datasets in a series should be connected to the series via `dcat:inSeries`. `dcat:next` was removed from DCAT-AP, as the [preferred of the two properties in DCAT](https://www.w3.org/TR/vocab-dcat-3/#inverse-properties) is `dcat:prev`.

That being said, currently, I do not see evidence of support for a relation similar to `dcat:prev` in the [INSPIRE Technical Guidelines](https://inspire-mif.github.io/technical-guidelines/metadata/metadata-iso19139/metadata-iso19139.html) that could map to `dcat:prev`.
I do not even see how a relation similar to `dcat:inSeries` is represented in the INSPIRE metadata, but I may be missing something.
