### ISSUE TITLE
Revise ambiguous `dct:type` mapping on Data Service

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/GeoDCAT-AP#77]
**Problem statement**

In GeoDCAT-AP 2.0.0 `dct:type` on Data Service is used in three different contexts.

1. [service category](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#data-service-service-category) with "Classification of spatial data services" code list
2. [service type](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#data-service-service-type) with "Spatial data service types" code list
3. [type](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#data-service-type) with "Resource types" code list. (this one also appears in Dataset)

This makes correct assignment of usage notes, labels and the required code lists rather difficult, as well as consequent validation e.g. via SHACL.
The current approach is not in line with the profiling guidelines established in the context of the SEMIC Style Guide property reuse guideline [Reuse of a property with terminological adaptations](https://semiceu.github.io/style-guide/1.0.0/clarification-on-reuse.html#sec:reuse-of-a-property-with-terminological-adaptations) and [Reuse of a property with semantic adaptations](https://semiceu.github.io/style-guide/1.0.0/clarification-on-reuse.html#sec:reuse-of-a-property-with-semantic-adaptations).
Also, the approach becomes even more problematic in a cross-profile environment where incompatible requirements can be easily made.

**Proposal**

Introduce subproperties of `dct:type`
1. `geodcatap:serviceCategory` for "Classification of spatial data services" code list
2. `geodcatap:serviceType` for "Spatial data service types" code list
3. `geodcatap:resourceType` for "Resource types" code list with the domain of `dcat:Resource` to accomodate both for Datasets and Data Services

This approach is in line with the profiling guidelines established in the context of the SEMIC Style Guide property reuse guideline [Reuse of a property with terminological adaptations](https://semiceu.github.io/style-guide/1.0.0/clarification-on-reuse.html#sec:reuse-of-a-property-with-terminological-adaptations) and [Reuse of a property with semantic adaptations](https://semiceu.github.io/style-guide/1.0.0/clarification-on-reuse.html#sec:reuse-of-a-property-with-semantic-adaptations).
If interoperability is a concern, a data publisher can always easily materialize the subPropertyOf inference and replace the subproperties with `dct:type`.

**Comment by jakubklimek** [comment]
Posponed until the next webinar

**Comment by joachimnielandt** [comment]
For info, in Flanders we are mapping to a subproperty of `dct:type` (related to #78 ):

| Eigenschap       | URI                                                         | GeoDCAT-AP | GeoDCAT-AP Vlaanderen      |
|------------------|-------------------------------------------------------------|------------|----------------------------|
| servicetype      | http://data.vlaanderen.be/ns/metadata-dcat#servicetype      | `dct:type` | subproperty van `dct:type` |
| servicecategorie | http://data.vlaanderen.be/ns/metadata-dcat#servicecategorie | `dct:type` | subproperty van `dct:type` |

**Comment by VeronikaKusova** [comment]
We had a discussion about this issue (Czech Office for Surveying, Mapping and Cadastre and Czech Environmental Information Agency) and we support the proposal - to create new subproperties of dct:type.
