### ISSUE TITLE
Define profile specific sub-property of `dct:subject`

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/GeoDCAT-AP#78]
**Problem statement**
The generic property `dct:subject` is used for specific code list "Topic categories in accordance with EN ISO 19115"​
(see [B.6.8.1 Topic category and keyword in datasets and dataset series](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#topic-category-and-keyword-in-datasets-and-dataset-series))​.

- Correct assignment of usage notes, labels and required code lists rather difficult, as well as validation​
- not in line with guidelines of SEMIC Style Guide​
  - [Reuse of a property with terminological ](https://semiceu.github.io/style-guide/1.0.0/clarification-on-reuse.html#sec:reuse-of-a-property-with-terminological-adaptations)[adaptations](https://semiceu.github.io/style-guide/1.0.0/clarification-on-reuse.html#sec:reuse-of-a-property-with-terminological-adaptations) or​
  - [Reuse of a property with semantic adaptations](https://semiceu.github.io/style-guide/1.0.0/clarification-on-reuse.html#sec:reuse-of-a-property-with-semantic-adaptations).​
- Even more problematic in a cross-profile environment - incompatible requirements can be easily made​

**Proposal**
Introduce subproperty of `dct:subject​` `geodcatap:topicCategory` for "Topic categories in accordance with EN ISO 19115" code list​.

**Comment by jakubklimek** [comment]
Posponed until the next webinar

**Comment by joachimnielandt** [comment]
For info, currently, in Flanders (Vlaanderen) the categorisations `ISO category`, `INSPIRE theme` and `GEMET concept` are mapped to a `dct:subject` subproperty for datasets:

| property      | URI                                                      | GeoDCAT-AP    | GeoDCAT-AP Vlaanderen     |
|---------------|----------------------------------------------------------|---------------|---------------------------|
| ISO Categorie | http://data.vlaanderen.be/ns/metadata-dcat#ISO-categorie | `dct:subject​` | subproperty `dct:subject​` |
| INSPIRE thema | http://data.vlaanderen.be/ns/metadata-dcat#INSPIRE-thema | `dcat:theme`  | subproperty `dct:subject` |
| GEMET concept | http://data.vlaanderen.be/ns/metadata-dcat#GEMET-concept | `dcat:theme​`  | subproperty `dct:subject` |

**Comment by VeronikaKusova** [comment]
We had a discussion about this issue (Czech Office for Surveying, Mapping and Cadastre and Czech Environmental Information Agency) and we agree with the proposal - to create new subproperty of dct:subject.
