### ISSUE TITLE
Usage of GeoDCAT-AP supporting tools

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/GeoDCAT-AP#80]
This issue serves the purpose of collecting usage evidence of the following GeoDCAT-AP supporting tools:

- [GeoDCAT-AP XSLT](https://github.com/SEMICeu/iso-19139-to-dcat-ap)
- [GeoDCAT](http://geodcat-ap.semic.eu/api/)[-AP API](http://geodcat-ap.semic.eu/api/)
- [CSW-4 Web](http://geodcat-ap.semic.eu/csw-4-web/)
- [EPSG-XSLT](http://github.com/SEMICeu/epsg-to-rdf/)
- [GeoIRI](https://geodcat-ap.semic.eu/geoiri/)
- [Measurement Resolution](https://geodcat-ap.semic.eu/id/resolution/scale/100)

If you use any of these tools, or if you definitely consider using them, please let us know about the context, in which you use/plan to use them.

In the introductory webinar to the revision of GeoDCAT-AP (2024-02-20) there was a poll on this topic, and the results indicated so far that only the [GeoDCAT-AP XSLT](https://github.com/SEMICeu/iso-19139-to-dcat-ap) is actually being used by the community. This is why we would like to take this opportunity to collect additional usage evidence of the tools.

**Comment by maudetes** [comment]
+1 for [GeoDCAT-AP XSLT](https://github.com/SEMICeu/iso-19139-to-dcat-ap) in France.

We plan to [add it in udata](https://github.com/opendatateam/udata/pull/2982) to parse ISO CSW graphs for harvesting purposes.

**Comment by jakubklimek** [comment]
The result of this evidence collection supports the findings from the webinar poll indicating, that only the XSLT is used of all the GeoDCAT-AP tools provided.
