### ISSUE TITLE
Agent-role distributor in Distribution context

### ISSUE THREAD

**Issue by joachimnielandt** [SEMICeu/GeoDCAT-AP#81]
In [https://semiceu.github.io/GeoDCAT-AP/releases/#agent-roles](https://semiceu.github.io/GeoDCAT-AP/releases/#agent-roles) a number of  agent roles are presented. A question arises when considering that there could be a more strict definition or expectation of a role within a specific context.

For instance, a distributor is a role about distributing a resource. That is clear for a Distribution as this is a precise specific instance of a Dataset. For a Dataset the semantics become a bit more fuzzy: is the distributor agent responsible for the distribution of all Distributions associated with a dataset?

Assessing the impact of the agent-roles and associating them with a preferred DCAT class could be discussed.

**Comment by jakubklimek** [comment]
@joachimnielandt just to clarify, do you suggest that GeoDCAT-AP would provide further guidance on which of these roles based on the [INSPIRE responsible party role code list](https://inspire.ec.europa.eu/metadata-codelist/ResponsiblePartyRole) are suitable for which of the DCAT classes - Dataset, Distribution, Data Service, Catalog instead of the current generic approach?

Do you have any specific suggestions?

**Comment by joachimnielandt** [comment]
Indeed, having some guideline on which role is applicable could be helpful. Where this information should be supplied, I don't know. For GeoDCAT-AP Vlaanderen (Flemish), the following was defined as the mapping, for example:

| ISO ScopeCode   | ISO(en)        | ISO(nl)     | Metadata DCAT     | GeoDCAT-AP     | URI (class) | card.  |
| ------- | -------------- | ----------- | ----------------- | ------------- | ------------------- | ------ |
| service | Custodian      | Beheerder   | Uitgever          | Publisher     | dct:publisher (dataservice)       | `1..1` |
| service | PointOfContact | Contactpunt | Contactinformatie | ContactPoint  | dcat:contactPoint (dataservice)   | `1..1` |
| dataset | Owner          | Eigenaar    |                   | Owner         | dct:rightsHolder (dataset)    | `0..1` |
| dataset | Owner      | Eigenaar    |                   | Publisher (1) | dct:publisher (dataset)       | `1..1` |
| dataset | Distributor    | Verdeler    |                   | Distributor   | geodcat:distributor (distribution) | `0..1` |
| dataset | PointOfContact | Contactpunt | Contactinformatie | ContactPoint  | dcat:contactPoint (dataset)   | `1..1` |
| dataset | Publisher      | Beheerder   | Uitgever          | Publisher     | dct:publisher (dataset)       | `1..1` |

(1) if `gmd:publisher` is missing we map the `gmd:owner` to `dct:publisher`, as this is semantically closest

**Comment by jakubklimek** [comment]
@joachimnielandt Your mapping basically corresponds to the mapping specified in GeoDCAT-AP [B.6.16 Responsible party and metadata point of contact - *Dataset responsible party and *Metadata point of contact](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#responsible-party-and-metadata-point-of-contact---dataset-responsible-party-and-metadata-point-of-contact) with the exception for Custodian, which GeoDCAT-AP maps to `geodcat:custodian` and you map it, for a service, to `dct:publisher`.

However, it is still a bit unclear to me, what exactly is your proposed improvement, as you mentioned that you would suggest Distributor to be used with Distributions, however, even in your mapping, it is used with a Dataset.

Could it maybe be boiled down to your original question
> Is distributor agent (specified on dataset) responsible for the distribution of all Distributions associated with a dataset?

?

Are there any rules like these in the INSPIRE guidelines?

**Comment by joachimnielandt** [comment]
@jakubklimek the table above might not have been clear enough - we have modified the header so that the first column indicates the ISO scopecode and the URI column contains the target dcat class.

The main takeaway would be the following line:

| ISO ScopeCode   | ISO(en)        | ISO(nl)     | Metadata DCAT     | GeoDCAT-AP     | URI (class) | card.  |
| ------- | -------------- | ----------- | ----------------- | ------------- | ------------------- | ------ |
| dataset | Distributor    | Verdeler    |                   | Distributor   | geodcat:distributor (distribution) | `0..1` |

**Comment by jakubklimek** [comment]
@joachimnielandt OK, so if I understand this correctly, you are saying that in your mapping rules, you have a mapping saying that a Distributor of a dataset in the ISO metadata is mapped to `geodcat:distributor` property on a `dcat:Distribution`, not a `dcat:Dataset`, whereas in GeoDCAT-AP 2.0.0 this is mapped to `geodcat:distributor` property on a `dcat:Dataset`.

And you propose to discuss, whether the `geodcat:distributor` should be moved from `dcat:Dataset` to `dcat:Distribution` and the mapping adjusted?

**Comment by joachimnielandt** [comment]
Indeed, discussing moving the attribute from `dcat:Dataset` to `dcat:Distribution` would be the proposal. Or at least a clarification of what if means to have a `distributor` on a `Dataset` level.

**Comment by jakubklimek** [comment]
Proposition was rejected during the webinar.
