### ISSUE TITLE
Relax `rights` max cardinality

### ISSUE THREAD

**Issue by joachimnielandt** [SEMICeu/GeoDCAT-AP#82]
In [https://semiceu.github.io/GeoDCAT-AP/releases/#optional-properties-for-catalogue](https://semiceu.github.io/GeoDCAT-AP/releases/#optional-properties-for-catalogue) (and more specific [https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Distribution.rights](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Distribution.rights)) there is a max-cardinality of 1 for rights. When mapping our ISO INSPIRE records we create multiple rights statements. This is because each statement in stored in the ISO records as an embedded statement and not as an external linked webpage.

Proposal: relaxing the max-cardinality for rights.

**Comment by jakubklimek** [comment]
Just to clarify the proposal, this would mean, as you already suggest, relaxing the cardinality also in DCAT-AP, not just GeoDCAT-AP, to keep the profiles compatible.

**Comment by jakubklimek** [comment]
During the webinar, the proposal to lift the cardinalities in GeoDCAT-AP and DCAT-AP was approved.
