### ISSUE TITLE
Reference system mapped to `dct:conformsTo`

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/GeoDCAT-AP#94]
**Problem statement**
In GeoDCAT-AP 2.0.0, the Reference system property on
- [Catalogue](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#catalogue-reference-system)
- [Data Service](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#data-service-reference-system)
- [Dataset](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#dataset-reference-system) and
- [Distribution](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#distribution-reference-system)

is mapped to the generic `dct:conformsTo`, which is also present on the same classes, both having `dct:Standard` as range.

This makes correct assignment of usage notes, labels and the required code lists rather difficult, as well as consequent validation e.g. via SHACL.
The current approach is not in line with the profiling guidelines established in the context of the SEMIC Style Guide property reuse guideline [Reuse of a property with terminological adaptations](https://semiceu.github.io/style-guide/1.0.0/clarification-on-reuse.html#sec:reuse-of-a-property-with-terminological-adaptations) and [Reuse of a property with semantic adaptations](https://semiceu.github.io/style-guide/1.0.0/clarification-on-reuse.html#sec:reuse-of-a-property-with-semantic-adaptations).
Also, the approach becomes even more problematic in a cross-profile environment where incompatible requirements can be easily made.

The reference system usage note says e.g. `This property SHOULD be used to specify the reference system used in the Catalogue. Spatial reference systems SHOULD be specified by using the corresponding URIs from the “EPSG coordinate reference systems” register operated by OGC [OGC-EPSG].`

The `dct:conformsTo` usage note says e.g. `This property refers to an implementing rule or other specification.`

**Proposal**
Either
1. Merge the usage notes to the generic `dct:conformsTo` to make it clear that reference systems are one kind of the Standards expected as values here, or
2. Introduce a profile specific subproperty of `dct:conformsTo` `geodcatap:referenceSystem` and attach the separate usage notes there.

**Comment by jakubklimek** [comment]
Posponed until the next webinar

**Comment by joachimnielandt** [comment]
Related issue / information: #115

**Comment by joachimnielandt** [comment]
As an applicable example, in Flanders we refer to the standard accompanied by a unique identifier. An example `conformsTo` element that refers to a standard is given below:

```xml
<dct:conformsTo>
        <dct:Standard rdf:about="https://www.opengis.net/def/crs/EjjPSG/0/5710">
                <dct:title>Ostend height</dct:title>
                <dct:identifier>https://www.opengis.net/def/crs/EPSG/0/5710</dct:identifier>
                <dct:type rdf:resource="http://inspire.ec.europa.eu/glossary/SpatialReferenceSystem"/>
        </dct:Standard>
</dct:conformsTo>
```

**Comment by jakubklimek** [comment]
A subproperty will be created.
