### ISSUE TITLE
Clarify meaning of multiple spatial / geographic coverages on a Data Service

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/GeoDCAT-AP#96]
**Problem statement**
The meaning of having multiple spatial / geographic coverages specified on one Data Service may not be clear enough.

**Proposal**
Add a usage note explicitly saying:
> If the Data Service provides access to multiple Datasets, then this will be the union of the spatial coverages of these Datasets.

**Comment by idevisser** [comment]
Just to be clear, can there be  only  one spatial coverage on one DataService, the the union of the spatial coverages of the available Datasets in this Data Service?

**Comment by jakubklimek** [comment]
Actually, this means that there can still be multiple values of spatial coverage on the DataService, but their interpretation resulting in the spatial coverage of the DataService will be a spatial union of those values.

**Comment by jakubklimek** [comment]
The proposal was accepted during the webinar.
